// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __ragt2ridges_h__
#define __ragt2ridges_h__

#include "ragt2ridges_RcppExports.h"

#endif // __ragt2ridges_h__
