// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// armaRidgePAnyTarget
arma::mat armaRidgePAnyTarget(const arma::mat& S, const arma::mat& target, const double lambda, int invert);
RcppExport SEXP ragt2ridges_armaRidgePAnyTarget(SEXP SSEXP, SEXP targetSEXP, SEXP lambdaSEXP, SEXP invertSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type target(targetSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type invert(invertSEXP);
    __result = Rcpp::wrap(armaRidgePAnyTarget(S, target, lambda, invert));
    return __result;
END_RCPP
}
// armaRidgePScalarTarget
arma::mat armaRidgePScalarTarget(const arma::mat& S, const double alpha, const double lambda, int invert);
RcppExport SEXP ragt2ridges_armaRidgePScalarTarget(SEXP SSEXP, SEXP alphaSEXP, SEXP lambdaSEXP, SEXP invertSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type invert(invertSEXP);
    __result = Rcpp::wrap(armaRidgePScalarTarget(S, alpha, lambda, invert));
    return __result;
END_RCPP
}
// armaRidgeP
arma::mat armaRidgeP(const arma::mat& S, const arma::mat& target, const double lambda, int invert);
RcppExport SEXP ragt2ridges_armaRidgeP(SEXP SSEXP, SEXP targetSEXP, SEXP lambdaSEXP, SEXP invertSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type target(targetSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type invert(invertSEXP);
    __result = Rcpp::wrap(armaRidgeP(S, target, lambda, invert));
    return __result;
END_RCPP
}
// armaRidgePchordalInitWorkhorse
arma::mat armaRidgePchordalInitWorkhorse(arma::mat S, const double lambda, arma::mat target, std::string type, Rcpp::List Cliques, Rcpp::List Separators);
RcppExport SEXP ragt2ridges_armaRidgePchordalInitWorkhorse(SEXP SSEXP, SEXP lambdaSEXP, SEXP targetSEXP, SEXP typeSEXP, SEXP CliquesSEXP, SEXP SeparatorsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type target(targetSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type Cliques(CliquesSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type Separators(SeparatorsSEXP);
    __result = Rcpp::wrap(armaRidgePchordalInitWorkhorse(S, lambda, target, type, Cliques, Separators));
    return __result;
END_RCPP
}
// armaPenLLreparPforNLM
Rcpp::NumericVector armaPenLLreparPforNLM(const arma::vec x, const arma::mat E1, const arma::mat E2, const arma::mat S, const double lambda, const arma::mat target, const arma::uvec nonzerosR, const arma::uvec nonzerosC);
RcppExport SEXP ragt2ridges_armaPenLLreparPforNLM(SEXP xSEXP, SEXP E1SEXP, SEXP E2SEXP, SEXP SSEXP, SEXP lambdaSEXP, SEXP targetSEXP, SEXP nonzerosRSEXP, SEXP nonzerosCSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type E1(E1SEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type E2(E2SEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type S(SSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type target(targetSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type nonzerosR(nonzerosRSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type nonzerosC(nonzerosCSEXP);
    __result = Rcpp::wrap(armaPenLLreparPforNLM(x, E1, E2, S, lambda, target, nonzerosR, nonzerosC));
    return __result;
END_RCPP
}
// armaPenLLreparP
const double armaPenLLreparP(const arma::vec x, const arma::mat E1, const arma::mat E2, const arma::mat S, const double lambda, const arma::mat target, const arma::uvec nonzerosR, const arma::uvec nonzerosC);
RcppExport SEXP ragt2ridges_armaPenLLreparP(SEXP xSEXP, SEXP E1SEXP, SEXP E2SEXP, SEXP SSEXP, SEXP lambdaSEXP, SEXP targetSEXP, SEXP nonzerosRSEXP, SEXP nonzerosCSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type E1(E1SEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type E2(E2SEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type S(SSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type target(targetSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type nonzerosR(nonzerosRSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type nonzerosC(nonzerosCSEXP);
    __result = Rcpp::wrap(armaPenLLreparP(x, E1, E2, S, lambda, target, nonzerosR, nonzerosC));
    return __result;
END_RCPP
}
// armaPenLLreparPgrad
arma::vec armaPenLLreparPgrad(const arma::vec x, const arma::mat E1, const arma::mat E2, const arma::mat S, const double lambda, const arma::mat target, const arma::uvec nonzerosR, const arma::uvec nonzerosC);
RcppExport SEXP ragt2ridges_armaPenLLreparPgrad(SEXP xSEXP, SEXP E1SEXP, SEXP E2SEXP, SEXP SSEXP, SEXP lambdaSEXP, SEXP targetSEXP, SEXP nonzerosRSEXP, SEXP nonzerosCSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type E1(E1SEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type E2(E2SEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type S(SSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type target(targetSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type nonzerosR(nonzerosRSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type nonzerosC(nonzerosCSEXP);
    __result = Rcpp::wrap(armaPenLLreparPgrad(x, E1, E2, S, lambda, target, nonzerosR, nonzerosC));
    return __result;
END_RCPP
}
// armaPenLLreparGradArchI
arma::vec armaPenLLreparGradArchI(const arma::vec x, const arma::mat E1, const arma::mat E2, const arma::mat S, const double lambda, const arma::mat target, const arma::uvec nonzerosR, const arma::uvec nonzerosC);
RcppExport SEXP ragt2ridges_armaPenLLreparGradArchI(SEXP xSEXP, SEXP E1SEXP, SEXP E2SEXP, SEXP SSEXP, SEXP lambdaSEXP, SEXP targetSEXP, SEXP nonzerosRSEXP, SEXP nonzerosCSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type E1(E1SEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type E2(E2SEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type S(SSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type target(targetSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type nonzerosR(nonzerosRSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type nonzerosC(nonzerosCSEXP);
    __result = Rcpp::wrap(armaPenLLreparGradArchI(x, E1, E2, S, lambda, target, nonzerosR, nonzerosC));
    return __result;
END_RCPP
}
// armaPenLLreparGradArchII
arma::vec armaPenLLreparGradArchII(const arma::vec x, const arma::mat E1, const arma::mat E2, const arma::mat S, const double lambda, const arma::mat target, const arma::uvec nonzerosR, const arma::uvec nonzerosC);
RcppExport SEXP ragt2ridges_armaPenLLreparGradArchII(SEXP xSEXP, SEXP E1SEXP, SEXP E2SEXP, SEXP SSEXP, SEXP lambdaSEXP, SEXP targetSEXP, SEXP nonzerosRSEXP, SEXP nonzerosCSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type E1(E1SEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type E2(E2SEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type S(SSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type target(targetSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type nonzerosR(nonzerosRSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type nonzerosC(nonzerosCSEXP);
    __result = Rcpp::wrap(armaPenLLreparGradArchII(x, E1, E2, S, lambda, target, nonzerosR, nonzerosC));
    return __result;
END_RCPP
}
// armaVAR1_ridgeML
Rcpp::List armaVAR1_ridgeML(Rcpp::NumericVector& Yraw, const double& lambdaA, const double lambdaP, arma::mat& targetA, arma::mat& targetP, std::string targetPtype, std::string fitA, arma::mat& unbalanced, bool& diagP, bool& efficient, const int& nInit, const double& minSuccDiff);
RcppExport SEXP ragt2ridges_armaVAR1_ridgeML(SEXP YrawSEXP, SEXP lambdaASEXP, SEXP lambdaPSEXP, SEXP targetASEXP, SEXP targetPSEXP, SEXP targetPtypeSEXP, SEXP fitASEXP, SEXP unbalancedSEXP, SEXP diagPSEXP, SEXP efficientSEXP, SEXP nInitSEXP, SEXP minSuccDiffSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type Yraw(YrawSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambdaA(lambdaASEXP);
    Rcpp::traits::input_parameter< const double >::type lambdaP(lambdaPSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type targetA(targetASEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type targetP(targetPSEXP);
    Rcpp::traits::input_parameter< std::string >::type targetPtype(targetPtypeSEXP);
    Rcpp::traits::input_parameter< std::string >::type fitA(fitASEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type unbalanced(unbalancedSEXP);
    Rcpp::traits::input_parameter< bool& >::type diagP(diagPSEXP);
    Rcpp::traits::input_parameter< bool& >::type efficient(efficientSEXP);
    Rcpp::traits::input_parameter< const int& >::type nInit(nInitSEXP);
    Rcpp::traits::input_parameter< const double& >::type minSuccDiff(minSuccDiffSEXP);
    __result = Rcpp::wrap(armaVAR1_ridgeML(Yraw, lambdaA, lambdaP, targetA, targetP, targetPtype, fitA, unbalanced, diagP, efficient, nInit, minSuccDiff));
    return __result;
END_RCPP
}
// armaVAR1_ridgeML_zerosA
Rcpp::List armaVAR1_ridgeML_zerosA(Rcpp::NumericVector Yraw, const double lambdaA, const double lambdaP, arma::mat targetA, arma::mat targetP, std::string targetPtype, std::string fitA, arma::mat unbalanced, bool diagP, bool efficient, const int nInit, const double minSuccDiff, const arma::uvec zerosR, const arma::uvec zerosC, std::string zerosAfit);
RcppExport SEXP ragt2ridges_armaVAR1_ridgeML_zerosA(SEXP YrawSEXP, SEXP lambdaASEXP, SEXP lambdaPSEXP, SEXP targetASEXP, SEXP targetPSEXP, SEXP targetPtypeSEXP, SEXP fitASEXP, SEXP unbalancedSEXP, SEXP diagPSEXP, SEXP efficientSEXP, SEXP nInitSEXP, SEXP minSuccDiffSEXP, SEXP zerosRSEXP, SEXP zerosCSEXP, SEXP zerosAfitSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Yraw(YrawSEXP);
    Rcpp::traits::input_parameter< const double >::type lambdaA(lambdaASEXP);
    Rcpp::traits::input_parameter< const double >::type lambdaP(lambdaPSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type targetA(targetASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type targetP(targetPSEXP);
    Rcpp::traits::input_parameter< std::string >::type targetPtype(targetPtypeSEXP);
    Rcpp::traits::input_parameter< std::string >::type fitA(fitASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type unbalanced(unbalancedSEXP);
    Rcpp::traits::input_parameter< bool >::type diagP(diagPSEXP);
    Rcpp::traits::input_parameter< bool >::type efficient(efficientSEXP);
    Rcpp::traits::input_parameter< const int >::type nInit(nInitSEXP);
    Rcpp::traits::input_parameter< const double >::type minSuccDiff(minSuccDiffSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type zerosR(zerosRSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type zerosC(zerosCSEXP);
    Rcpp::traits::input_parameter< std::string >::type zerosAfit(zerosAfitSEXP);
    __result = Rcpp::wrap(armaVAR1_ridgeML_zerosA(Yraw, lambdaA, lambdaP, targetA, targetP, targetPtype, fitA, unbalanced, diagP, efficient, nInit, minSuccDiff, zerosR, zerosC, zerosAfit));
    return __result;
END_RCPP
}
// armaEigenDecomp_blockDiagOnly_forR
Rcpp::List armaEigenDecomp_blockDiagOnly_forR(const arma::mat symMat, const arma::ivec blockDims);
RcppExport SEXP ragt2ridges_armaEigenDecomp_blockDiagOnly_forR(SEXP symMatSEXP, SEXP blockDimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat >::type symMat(symMatSEXP);
    Rcpp::traits::input_parameter< const arma::ivec >::type blockDims(blockDimsSEXP);
    __result = Rcpp::wrap(armaEigenDecomp_blockDiagOnly_forR(symMat, blockDims));
    return __result;
END_RCPP
}
// armaVAR1_Shat_ML_forR
arma::mat armaVAR1_Shat_ML_forR(Rcpp::NumericVector Yraw, const arma::mat A);
RcppExport SEXP ragt2ridges_armaVAR1_Shat_ML_forR(SEXP YrawSEXP, SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Yraw(YrawSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type A(ASEXP);
    __result = Rcpp::wrap(armaVAR1_Shat_ML_forR(Yraw, A));
    return __result;
END_RCPP
}
// armaVAR1_COVYhat_forR
arma::mat armaVAR1_COVYhat_forR(Rcpp::NumericVector Yraw);
RcppExport SEXP ragt2ridges_armaVAR1_COVYhat_forR(SEXP YrawSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Yraw(YrawSEXP);
    __result = Rcpp::wrap(armaVAR1_COVYhat_forR(Yraw));
    return __result;
END_RCPP
}
// armaVAR1_VARYhat_forR
arma::mat armaVAR1_VARYhat_forR(Rcpp::NumericVector Yraw, bool efficient, arma::mat unbalanced);
RcppExport SEXP ragt2ridges_armaVAR1_VARYhat_forR(SEXP YrawSEXP, SEXP efficientSEXP, SEXP unbalancedSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Yraw(YrawSEXP);
    Rcpp::traits::input_parameter< bool >::type efficient(efficientSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type unbalanced(unbalancedSEXP);
    __result = Rcpp::wrap(armaVAR1_VARYhat_forR(Yraw, efficient, unbalanced));
    return __result;
END_RCPP
}
// armaVAR1_Ahat_zeros_forR
arma::mat armaVAR1_Ahat_zeros_forR(const arma::mat& P, arma::mat& COVY, const arma::mat& eigvecVARY, const arma::vec& eigvalVARY, const double& lambdaA, const arma::mat& targetA, std::string fitA, const arma::uvec& zerosR, const arma::uvec& zerosC, std::string& zerosAfit);
RcppExport SEXP ragt2ridges_armaVAR1_Ahat_zeros_forR(SEXP PSEXP, SEXP COVYSEXP, SEXP eigvecVARYSEXP, SEXP eigvalVARYSEXP, SEXP lambdaASEXP, SEXP targetASEXP, SEXP fitASEXP, SEXP zerosRSEXP, SEXP zerosCSEXP, SEXP zerosAfitSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type P(PSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type COVY(COVYSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type eigvecVARY(eigvecVARYSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type eigvalVARY(eigvalVARYSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambdaA(lambdaASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type targetA(targetASEXP);
    Rcpp::traits::input_parameter< std::string >::type fitA(fitASEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type zerosR(zerosRSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type zerosC(zerosCSEXP);
    Rcpp::traits::input_parameter< std::string& >::type zerosAfit(zerosAfitSEXP);
    __result = Rcpp::wrap(armaVAR1_Ahat_zeros_forR(P, COVY, eigvecVARY, eigvalVARY, lambdaA, targetA, fitA, zerosR, zerosC, zerosAfit));
    return __result;
END_RCPP
}
// armaP_defaultTarget_forR
arma::mat armaP_defaultTarget_forR(arma::mat S, std::string targetType, const double fraction, double const multiplier);
RcppExport SEXP ragt2ridges_armaP_defaultTarget_forR(SEXP SSEXP, SEXP targetTypeSEXP, SEXP fractionSEXP, SEXP multiplierSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    Rcpp::traits::input_parameter< std::string >::type targetType(targetTypeSEXP);
    Rcpp::traits::input_parameter< const double >::type fraction(fractionSEXP);
    Rcpp::traits::input_parameter< double const >::type multiplier(multiplierSEXP);
    __result = Rcpp::wrap(armaP_defaultTarget_forR(S, targetType, fraction, multiplier));
    return __result;
END_RCPP
}
// armaVAR_array2cube_withMissing_forR
arma::cube armaVAR_array2cube_withMissing_forR(Rcpp::NumericVector& Yraw, const arma::uvec& unbalancedR, const arma::uvec& unbalancedC);
RcppExport SEXP ragt2ridges_armaVAR_array2cube_withMissing_forR(SEXP YrawSEXP, SEXP unbalancedRSEXP, SEXP unbalancedCSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type Yraw(YrawSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type unbalancedR(unbalancedRSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type unbalancedC(unbalancedCSEXP);
    __result = Rcpp::wrap(armaVAR_array2cube_withMissing_forR(Yraw, unbalancedR, unbalancedC));
    return __result;
END_RCPP
}
// armaVAR_array2cube_withoutMissing_forR
arma::cube armaVAR_array2cube_withoutMissing_forR(Rcpp::NumericVector& Yraw);
RcppExport SEXP ragt2ridges_armaVAR_array2cube_withoutMissing_forR(SEXP YrawSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type Yraw(YrawSEXP);
    __result = Rcpp::wrap(armaVAR_array2cube_withoutMissing_forR(Yraw));
    return __result;
END_RCPP
}
// armaEigenDecomp_forR
Rcpp::List armaEigenDecomp_forR(const arma::mat symMat);
RcppExport SEXP ragt2ridges_armaEigenDecomp_forR(SEXP symMatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat >::type symMat(symMatSEXP);
    __result = Rcpp::wrap(armaEigenDecomp_forR(symMat));
    return __result;
END_RCPP
}
// armaVAR1_convergenceEvaluation_forR
const double armaVAR1_convergenceEvaluation_forR(arma::mat Ahat, arma::mat Aprev, arma::mat Phat, arma::mat Pprev);
RcppExport SEXP ragt2ridges_armaVAR1_convergenceEvaluation_forR(SEXP AhatSEXP, SEXP AprevSEXP, SEXP PhatSEXP, SEXP PprevSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type Ahat(AhatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Aprev(AprevSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Phat(PhatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Pprev(PprevSEXP);
    __result = Rcpp::wrap(armaVAR1_convergenceEvaluation_forR(Ahat, Aprev, Phat, Pprev));
    return __result;
END_RCPP
}
// armaVAR1_Ahat_ridgeML_forR
arma::mat armaVAR1_Ahat_ridgeML_forR(arma::mat P, arma::mat COVY, const arma::mat eigvecVARY, const arma::colvec eigvalVARY, const double lambdaA, arma::mat targetA);
RcppExport SEXP ragt2ridges_armaVAR1_Ahat_ridgeML_forR(SEXP PSEXP, SEXP COVYSEXP, SEXP eigvecVARYSEXP, SEXP eigvalVARYSEXP, SEXP lambdaASEXP, SEXP targetASEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type P(PSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type COVY(COVYSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type eigvecVARY(eigvecVARYSEXP);
    Rcpp::traits::input_parameter< const arma::colvec >::type eigvalVARY(eigvalVARYSEXP);
    Rcpp::traits::input_parameter< const double >::type lambdaA(lambdaASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type targetA(targetASEXP);
    __result = Rcpp::wrap(armaVAR1_Ahat_ridgeML_forR(P, COVY, eigvecVARY, eigvalVARY, lambdaA, targetA));
    return __result;
END_RCPP
}
// armaVAR1_Ahat_ridgeSS_forR
arma::mat armaVAR1_Ahat_ridgeSS_forR(arma::mat COVY, arma::mat VARY, const double& lambdaA, arma::mat& targetA);
RcppExport SEXP ragt2ridges_armaVAR1_Ahat_ridgeSS_forR(SEXP COVYSEXP, SEXP VARYSEXP, SEXP lambdaASEXP, SEXP targetASEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type COVY(COVYSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type VARY(VARYSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambdaA(lambdaASEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type targetA(targetASEXP);
    __result = Rcpp::wrap(armaVAR1_Ahat_ridgeSS_forR(COVY, VARY, lambdaA, targetA));
    return __result;
END_RCPP
}
// armaVAR1_loglikLOOCVinternal_forR
const double armaVAR1_loglikLOOCVinternal_forR(arma::vec Yt1, arma::vec Yt0, arma::mat A, arma::mat P);
RcppExport SEXP ragt2ridges_armaVAR1_loglikLOOCVinternal_forR(SEXP Yt1SEXP, SEXP Yt0SEXP, SEXP ASEXP, SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type Yt1(Yt1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yt0(Yt0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type P(PSEXP);
    __result = Rcpp::wrap(armaVAR1_loglikLOOCVinternal_forR(Yt1, Yt0, A, P));
    return __result;
END_RCPP
}
// armaVAR1_loglik_forR
const double armaVAR1_loglik_forR(Rcpp::NumericVector Yraw, arma::mat A, arma::mat P);
RcppExport SEXP ragt2ridges_armaVAR1_loglik_forR(SEXP YrawSEXP, SEXP ASEXP, SEXP PSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Yraw(YrawSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type P(PSEXP);
    __result = Rcpp::wrap(armaVAR1_loglik_forR(Yraw, A, P));
    return __result;
END_RCPP
}
